version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - setup_remote_docker:
          version: 19.03.13
      - run: 
          name: Run Docker Container
          command: |
            docker run -d --name my-app nginx
            docker exec my-app curl --retry 10 --retry-connrefused http://localhost:80
